:lang: no
:doctitle: Introduksjon til kapabilitetskart for nasjonal arkitektur
:keywords: eMelding
:toclevels: 3
include::../plattform_felles/includes/commonincludes.adoc[]

Den totale virksomhetsarkitekturen inndeles i områder, eller temaområder, og videre i kapabiliteter. Dette kan gjøres i flere nivåer, til et hensiktsmessig detaljnivå. 

Se videre informasjon om link:../nab_overordnet-metode[temaområder og kapabilitetskart] under link:../nab_overordnet-metode[Grunnleggende konsepter for Nasjonalt arkitekturbibliotek].



////

Erik 26/6: Hvem skrev dette uten å snakke med meg først? Her rotes det til med nye begreper, diverse bakgrunnsiformasjon og omtale av "deling av data" på feil sted. Denne introduksjonen ønsker jeg kort og konsis, helt overordnet og generell for alle temaområdene. Konsepter,metodikk og bakgrunnsinformasjon skal være beskrevet annet sted (under "metodikk og rammeverk"). Sørskilt info om deling av data må ligge under det kapitlet som dreier seg om deling av data.  
---

Inndeling i _temaområder_ tilsvarer det som TOGAF 9.2 på engelsk kaller _"subject areas"_ eller _segments_. Dette kan ses på som en gruppering av kapabiliteter som en ønsker å adressere samlet, enten gjennom gjennom _referansearkitekturer_ eller mer spesifikke __segmentarkitekturer__.


Overordnede temaområder brytes ned i mer spesifikke områder, ned til konkrete kapabiliteter på laveste nivå. For hver kapabilitet angis aktører eller roller (mennesker eller systemer) som kapabiliteten gjelder for.


Inndelingen er ment å gi en klassifisering for kapabiliteter. De øverste nivåene er stabile over tid når det gjelder området deling av data. Vokabularet for kapabilitetene vil derimot utvikles over tid.

Det er hovedsakelig to ulike viewpoints hvor det vil være relevant å gi oversikt over kapabiliteter.

* Det første er som del i kapabilitetskartlegging etter kategori. Deretter gir man oversikter over enkeltdeler av en klassifisering.

* Den andre er oversikter over kapabiliteter knyttet til et prosjekt eller en løsning, hvor man kobler eller grupperer kapabilitetene etter aktøren eller rollen som er knyttet til kapabiliteten. 

I tillegg er det tverrgående områder («cross-cutting layers») som vil inngå i realiseringen av øvrige kapabilitetsområder. Det er avhengigheter mellom områdene.  

Formålet er å kunne jobbe effektivt med referansearkitekturer for deling av data.

Det er behov for et kapabilitetskart for bl.a. å se referansearkitekturer i sammenheng, kunne vite hvor en jobber i det store bildet, og for å unngå dobbeltarbeid og at lignende løsning blir laget flere ganger i forvaltningen. 
////    