:lang: no
:doctitle: Dokumentasjonsmaler
:keywords: Norsk, arkitekturbibliotek, maler

:toclevels: 4

include::../plattform_felles/includes/commonincludes.adoc[]

[.lead]
Maler for dokumentasjon i form av tekst, multimedia og arkitekturmodeller


== Generelt
Dokumentasjonsmaler finnes i form av:

. Verktøyspesifikke viewpoints for modellering i aktuelle modelleringsspråk; slik som f.eks. Archimate-modeller i verktøyet Archi. 

. Dokumentmaler for tekst og multimeda i verktøy som Asciidoc, Google Docs, m.m.


NOTE: Se også annet innhold om verktøyuavhengige dokumentasjonskonvensjoner.



== Maler for dokumentasjon i Asciidoc


=== Bokmaler
. link:../nab_referanse_maler_asciidoc-book-basic[Basic Asciidoc Book Template]


=== Artikkelmaler
NOTE: Artikler kan opptre som separate artikler med egen innholdsfortegnelse, eller som del av bøker sammen med andre artikler (eller kapitler).

. link:../nab_referanse_maler_asciidoc-articles/template_basic_article.adoc[Basic article]


=== Maler for dokumentasjon av referansearkitektur i Asciidoc

. link:../nab_referanse_maler_asciidoc-book-sat[Solution Architecture Template]

== Archi viewpoints
TBD.