:lang: no
:doctitle: Kilder til kunnskap om Archimate 
:keywords: Archimate

include::../plattform_felles/includes/commonincludes.adoc[]

[.lead]
Utvalgte ressurser for å lære om Archimate.




== Om Archimate-standarden som sådan
=== Standardspesifikasjonen fra The Open Group
Selve standarden finnes online her: link:http://pubs.opengroup.org/architecture/archimate3-doc/[ArchiMate® 3.0.1 Specification]

=== Pocket guide fra The Open Group
Nedlastbar pdf gratisversjon av link:https://www.slideshare.net/pafaxaxaku/free-download-archimate-30-a-pocket-guide-the-open-group-series-book-online?qid=f9f116a7-950d-4785-b731-3f45c071bdf9&v=&b=&from_search=7[ArchiMate 3.0 - A Pocket Guide]. Merk: Siste versjon av A Pocket Guide to the ArchiMate® 3.0.1 Specification (PDF) kan eventuelt kjøpes link:https://shop.opengroup.org/g163[her] (men det er ikke store forskjeller).

=== Oppsummering av konsepter i Archimate 3.0
link:https://1drv.ms/b/s!Ao0VyYhs1XdLjkHTIqOywoRdBHCk[Oppsummering av konsepter i Archimate 3.0]



=== Bok: Mastering Archimate
link:https://ea.rna.nl/the-book-edition-iii/?cp=1_2[Mastering ArchiMate – Edition III]

Denne boken blir av mange ansett som en slags "bibel" for de som vil forstå Archimate i dybden. Forfatteren, Gerben Wierda fra Nederland, har skrevet flere bøker om virksomhetsarkitektur, og er en kapasitet på området.

Deler av boken være tung for mange? 

Legg spesielt merke til at Gerben anvender en egen konvensjon for fargelegging av symboler. Dette er helt innenfor standarden og gir ekstra mening, men kan også være egnet til forvirring for de mange som f.eks. tenker at gult betyr "business".  

En uoffisiell kopi av denne boken finnes midlertidig link:https://1drv.ms/b/s!Ao0VyYhs1XdLhaRk49fJtXe_mRG3eA[her]. 


== Online opplæringsmateriell 

. link:http://www.biner.no/kurs/archimate-elearning[Biner Archimate e-learning]

. Udemy Archimate 3.0 kræsjkurs
https://www.udemy.com/archimate-3-crash-course/learn/v4/content

. ArchiMate Tutorial fra Visual Paradigm
https://online.visual-paradigm.com/tutorials/archimate-tutorial/


== Klasseromskurs
Bouvet, Biner, ...

== Blogger og diskusjonsgrupper
=== Kilder

1. link:https://www.linkedin.com/groups/50758/[LinkedIn-gruppe Archimate]. 


=== Noen eksempler på blogger og diskusjoner

http://weblog.tetradian.com/2015/02/10/on-modelling-selfservice-w-archimate/            


== Annet
===  Technology Base Reference Models for Open Platform 3.0™
The Open Group utga i 2017 en standard ved navn __Technology Base Reference Models for Open Platform 3.0™__.

Standarden sier: "It specifies basic architecture models in which platforms interact with each other and with other system components."

Ressurser:

. link:https://1drv.ms/b/s!Ao0VyYhs1XdLhc0J9VFSjTVqOvu_1g[PDF-versjon av Technology Base Reference Models for Open Platform 3.0™]

. link:http://www.opengroup.org/openplatform3.0/op3-snapshot/p6.htm[Online utdrag av standarden, med Archimate-modellene].



