:lang: no
:author: Rolf Rander Næss
:email: rolf.rander.ness@acando.no
:doctitle_no: Overordnet innføring i sikkerhetsmekanismer for eOppslag
:keywords: eOppslag sikkerhet autentisering

include::../plattform_felles/includes/commonincludes.adoc[]


== Overordnede mål

Sikkerhetsarkitekturen for eOppslag er laget med tanke på å nå følgende overordnede målsetninger:

* Standardiserte sikkerhetsnivå med definerte sett av sikkerhetsmekanismer, slik at det er mulig å velge grad av sikkerhet tilpasset en risikovurdering av tjenesten det gjelder.
* Standardisert mekanisme for autentisering av klienter for å få teknisk konsolidering på tvers av offentlig sektor og mulighet til gjenbruk av komponenter
* Standardisert mekanisme for delegering av myndighet, hvor en virksomhet kaller tjenester på vegne av en annen virksomhet

I tillegg er følgende tekniske forutsetninger lagt til grunn:

* Vi ønsker å redusere bruken av virksomhetssertifikat, og heller bruke en mekanisme som kan begrenses i gyldighetsområde og -tidsrom.
* Det er behov for en mekanisme som kan integreres i HTTP og som virker gjennom proxy/gateway-løsninger på en transparent måte.
* Vi ønsker også en mekanisme som i størst mulig grad er standardisert, slik at vi kan gjenbruke eksisterende infrastruktur for håndtering av token-mekanismer og applikasjoner integrert mot denne.

I arbeidet med sikkerhetsarkitekturen er det antatt at eOppslag kun dreier seg om synkrone "request-reply"-tjenester for å lese informasjon. Skrive-tjenester, eller "request-reply" brukt som et element i en større protokoll er ikke diskutert.

Disse er beskrevet i mer detalj i det følgende

== Standardiserte sikkerhetsnivå

Referansearkitekturen definerer følgende standardiserte sikkerhetsnivå, men det er opp til API-tilbyder å velge hvilket nivå som er passende for en gitt tjeneste. Hvert nivå bygger på det foregående ved at hvert nivå inkluderer mekanismene gitt i forrige nivå.

* Nivå 0: kryptert kanal, men ingen autentisering av klienten. Dette innebærer bruk av TLS (https) som gir integritet og konfidensialitet for trafikk rutet over åpne nett, samt autentisering av API-tilbyder
* Nivå 1: autentisering av klienten. Mesteparten av dette dokumentet beskriver denne autentiseringsmekanismen.
* Nivå 2: integritetskontroll på meldingsnivå, typisk gjennom bruk av digitale signaturer som signerer meldingen uavhengig av transportkanalen
* Nivå 3: kryptering på meldingsnivå

Nivå 2 og 3 forutsetter en strategi for distribusjon og håndtering av nøkler og sertifikater, dette er foreløpig ikke definert i denne referansearkitekturen.

== Standardisert autentiseringsmekanisme

Autentisering i denne sammenheng innebærer at en klient autentiseres som den virksomheten den representerer, identifisert med organisasjonsnummer. Arkitekturen tar ikke høyde for å skille mellom ulike klienter internt i samme virksomhet, det er forventet at virksomheten selv håndterer styring av hvilke klienter som får kalle hvilke tjenester gjennom sin egen integrasjonsarkitektur og sikkerhetsarkitektur. Det er utenfor rammen av denne referansearkitekturen å gi føringer for hvordan dette skal løses.

På bakgrunn av de tekniske forutsetningene velger vi i denne referansearkitekturen en autentisering hvor:

* Klienten autentiserer seg mot en token-tjeneste med et virksomhetssertifikat.
* Token-tjenesten utsteder et token som kun er gyldig for et begrenset tidsrom mot en spesifisert tjeneste.
* Tokenet brukes som autentisering mot aktuell tjeneste.

Denne løsningen gjør også at vi har fleksibilitet til å innføre andre autentiseringsmekanismer eller støtte for andre typer sertifikat senere.

Bruk av token på denne måten oppfyller også de tekniske føringene:

* Bruk av virksomhetssertifikatet reduseres til kun å utstede token, virksomhetssertifikatet brukes ikke direkte mot hver enkelt tjeneste klienten ønsker å kalle.
* Bruk av proxy/gateway-løsninger innebærer at TLS-forbindelsen termineres i en gateway og en ny forbindelse settes opp for videre kommunikasjon. Autentiseringsmekanismer knyttet til TLS-forbindelsen blir dermed ikke videreformidlet inn mot bakenforliggende tjenester, men må kontrolleres av gateway-en. Løsningen som foreslås her innebærer i stedet at autentiseringsmekanismen legges i en http-header og kan videreformidles gjennom gateway/proxy inn til tjenesten som kalles.
* Gjennom å implementere token-tjenesten med standard OAuth2- og JWT-mekanismer finnes det hyllevare for å ta imot, verifisere og konvertere slike tokens.

== Delegering av myndighet

Dette er nyttig i mange situasjoner og en felles løsning for dette på tvers av offentlig sektor vil kunne gi stor gevinst, for eksempel i situasjoner som:

* Regnskapskontor, advokater, meglere osv opptrer på vegne av sine oppdragsgivere
* Tjenesteleverandører, driftsleverandører eller aggregeringstjenester opptrer på vegne av sine kunder
* Bransjeorganisasjoner opptrer på vegne av sine medlemmer

I den videre diskusjonen trenger vi å skille mellom:

* Konsumenten (C) som er den juridiske ansvarlige for bruken av tjenesten og den som i siste instans får informasjonen som etterspørres
* Leverandøren (L) er den som kontrollerer klienten og som faktisk kaller tjenesten på vegne av konsument (C).

Referansearkitekturen legger her opp til:

* Tilgangsstyringen i tjenesten er uavhengig av hvem som er leverandøren, det er kun konsumenten som er relevant
* Klienten autentiserer seg til token-tjenesten som leverandør, men sier samtidig at den ønsker tilgang til en bestemt tjeneste på vegne av konsument
* Token-tjenesten vil bare utstede et token dersom begge disse holder:
** Konsumenten er autorisert for å kalle tjenesten, dette styres av API-tilbyder
** Leverandøren er autorisert til å opptre på vegne av konsumenten for denne tjenesten, dette styres av konsumenten
* Tokenet som genereres vil inneholde identitet til både konsument og leverandør, men det er forutsatt at informasjon om leverandøren kun brukes til sporingsformål (logging).
