////
Guide to the below header attributes:

    lang: en; no
    difi_orig_language: en; no
    difi_translation_status: -; missing; incomplete; OK 
    keywords_en: comma separated list of english keywords (no controlled vocabulary); TBD
    keywords_no: comma separated list of Norwegian keywords (no controlled vocabulary); TBD  
    
Note: The _lang_ value may be overridden by a command line parameter.
////

:lang: en
:difi_orig_language: en
:doctitle_en: The Event-Driven Architecture paradigm
:doctitle_no: Hendelsesdrevet arkitekturparadigme
:difi_translation_status: -
:keywords_en: TBD
:keywords_no: TBD
:toclevels: 3
:difi_doctype: Basic Book Template


// The above parameters are processed by scripts included by the following statement
include::../plattform_felles/includes/commonincludes.adoc[]


[.lead]
Event-Driven Architecture...

////
////

:leveloffset: +1
[#intro]
= Introduction
There are numerous sources that will explain the concepts of _Events_ and _Event-Driven Architecture_, in general or in context with e.g. some sort of Service-Oriented Architecture.


[[event-driven]]
= Resources

Here are some sources that could be useful to gain insight and serve as common ground:

. link:https://en.wikipedia.org/wiki/Event-driven_SOA[Wikipedia on Event-driven SOA]
+
SOA 2.0 is the ability to create high-level business events from numerous low-level system events. Events are created by filtering real-time data (from middleware, applications, databases, and Web services, for example) and infusing it with defining detail such as dependencies or causal relationships discovered by correlating other events.
+
SOA 2.0 event-driven programming is structured around the concept of [underline]##decoupled relationships between event producers and event consumers##: an event consumer doesn't care where or why an event occurs; rather, it's concerned that it will be invoked when the event has occurred. Systems and applications that separate event producers from event consumers typically rely on an [underline]##event dispatcher, or channel##. This channel contains an event queue that acts as an intermediary between event producers and event handlers.
+
SOA 2.0 event patterns can be designed and implemented to look for event relationships that span days, weeks, or months; and when certain criteria are met, trigger a business process to address the event pattern.


. link:https://en.wikipedia.org/w/index.php?title=Event-driven_architecture&oldid=915117327[Wikipedia on Event-driven architecture]

. link:https://www.confluent.io/blog/journey-to-event-driven-part-1-why-event-first-thinking-changes-everything[A series of four articles about the Journey to Event Driven]
. link:https://martinfowler.com/articles/201701-event-driven.html[2017 blog article by MartinFowler: What do you mean by “Event-Driven”? ]


. https://medium.com/@hugo.oliveira.rocha/what-they-dont-tell-you-about-event-sourcing-6afc23c69e9a[What they don’t tell you about event sourcing]


