:lang: no
:attr_orig_language: no
:attr_translation_status: incomplete
:revdate: 2018-08-06
:doctitle_en: Introduction to Documentation conventions 
:doctitle_no: Introduksjon til dokumentasjonskonvensjoner
:keywords_no: dokumentasjon, konvensjoner, retningslinjer
:keywords_en: documentation, conventions, guidelines

include::../na_felles/includes/standardheader.adoc[]
include::../na_felles/includes/commonlinks1.adoc[]


== Generelt om dokumentasjonsformater, lagringsmedia og verktøy 

Eksisterende innhold i diverse formater og verktøy for tekst og multimedia bør kunne lenkes til fra innhold og oversikter i det GitHub-baserte arkitekturbiblioteket, uten at filene flyttes tli GitHub eller konverteres til nye formater. Se #TBD# for mer om dette.

Alt nytt innhold skal lagres på gjeldende standard innholdsformater, som er: 

* Tekst og multimedia: Både Markdown og Asciidoc kan benyttes, men Asciidoc anbefales. Begge disse formatene støttes på GitHub, dvs. at kildefilene kan vises direkte med en layout som er nær opp til det en vil få ved generering av resultatfiler i html. Markdown er per 2018 mest utbredt blant utviklere, men har visse begrensinger. Asciidoc gir større muligheter samtidig som det er (nesten) like lett å komme igang med som Markdown for enkle formål.
+
Som format for bildefiler anbefales svg.
+
Video: #TBD#

NOTE: Mange  har sterke synspunkter om hva som burde være "vår" standard - Markdown eller Asciidoc. Dette er bakgrunnen for at det i det minste inntil videre åpnes for begge deler, selv om det gir risiko for ekstrajobb med opprydding i neste omgang. Det viktigste er uansett at "alle" som vil dokumentere, får det gjort.   


* Arkitekturmodellering: Arcimate-standarden benyttes som notasjon. Modellene skal tilgjengeliggjøres i html-format, i tillegg til lagring på  standard Archimate utvekslingsformat. Dessuten skal modellene lagres på det originale formatet de ble produsert i. Det er også ønskelig at det gjøres konvertering til formater som kan åpnes direkte i de de mest utbredte verktøyene (per 2018 Archi og eventuelt Spacrx Enterprise Architect).

* Prosessmodeller: BPMN...

* Datamodeller: UML Class Diagrams...

* Regelmodellering: DMN...


Ut fra standardformatene i biblioteket kan det enkelt konverteres til andre formater for publisering eller videre arbeid. For publisering benyttes i utgangspunktet primært html5.

Tidligere dokumentasjon i andre formater konvereres til gjeldende standarder ut fra kost-nytte-vurderinger. Det finnes f.eks. verktøy for konverting av Word-dokumenter til asciidoc, men noe manuelt arbeid må en uansett regne med. 

Dokumentasjon i andre formater enn standard Asciidoc (eller Markdown) som inngår som en integret del av det nasjonale arkitekturbiblioteket, slik som f.eks. Word eller pdf, lagres i Onedrive i tilsvarende mappestruktur som i GitHub og kan lenkes til som ønsket.

NOTE: Det er mulig å lagre tradisjonelle dokumenter på github, slik som f.eks Word eller pdf, men dette gjøres i minst mulig grad. Andre teknologier er bedre egnet enn GitHub for lagring og søk i dokumenter. Total størrelse på Github-biblioteket bør dessuten begrenses, slik at det lar seg klone til den enkeltes lokale filområde (det er slik en jobber med innhold i github). 

== Innholdsproduksjon i Markdown format
Marddown kan brukes 

== Innholdsproduksjon i Asciidoc format
#TBD.#

== Archimate-modellering
#TBD.#

== BPMN-modellering
#TBD.#

== UML-modellering
#TBD.#

== Annet
* Risikomodellering: #TBD#
* ...
 
