:lang: no
:doctitle: Referansearkitekturer for datautveksling
:keywords: Referansearkitektur
:toclevels: 3
include::../plattform_felles/includes/commonincludes.adoc[]

== Introduksjon
=== Generelt
Referansearkitekturer for datautveksling omfatter generiske arkitekturmønstre som beskriver tverrgående temaer, samt mer løsningsspesifikke mønstre.

=== Avgrensing
Referansearkitekturer og mønstre for datautveksling dekker i hovedsak selve utvekslingen av data og dokumenter. 

Bruken av data i forretningsprosesser og dataanalyse dekkes i utangspunktet ikke, med mindre det er relevant for måten datautvekslingen gjøres på. I forbindelse med datavirtualisering, er det f.eks. mulig å gjøre dataanalyse der dataene ligger, og så innhente analyseresultater i stedet for rådata.

Begrepet data dekker i denne sammenhengen også dokumenter og bevis. Se under "Hva er data" for nærmere presisering av disse begrepene.

Det finnes en rekke temaer og forutsetninger for at datautveksling skal fungere. Noen av disse temaene er store og dekkes ikke generelt som del av denne referansearkitekturen, slik som informasjonsforvaltning, datakvalitet og identitettsforvaltning . Det er likevel elementer innen disse temaene som er spesielt relevante og derfor omghandles, enten som tverrgående temaer under generiske mønstre eller i tilknytning til mer spesifikke løsningsmønstre.

En introduksjon til aktuelle temaer er gitt under kap. x. Nærmere informasjon om utvalgte temaer oppdateres fortløpende.

== Hva er data?
include::../nab_referanse_arkitekturer_datautveksling/hva-er-data.adoc[]

== Overordnet forretningmessig kontekst
include::../nab_referanse_arkitekturer_datautveksling/overordnet-forretningsmessig-kontekst.adoc[]

//== Strategi
//TBD.

== Brukstilfeller
include::../book-tverrgående-tema.adoc[]


== Overgripende modell for datautveksling

=== Generisk prosess for klargjøring til databehandling

include::../nab_referanse_arkitekturer_datautveksling/generisk-prosess-for-klargjøring-til-databehandling.adoc[]

=== Generisk prosess for operativ databehandling
include::../nab_referanse_arkitekturer_datautveksling/generisk-prosess-for-operativ-databehandling.adoc[]


== Prinsipper
TBD. (Ta inn referanser til nasjonale pribsipper; under revidering. Husk TOOP!)

== Introduksjon til tverrgående temaer
include::../nab_referanse_arkitekturer_tverrgående-tema/book-tverrgående-tema.adoc[]
////
Foreløpg liste over temaer:

Merk: Dette er i arbeid. Beskrives som kapabiliteter.

* Logging

* Tidsstempling

* Fellesskapsforvaltning

* Informasjonssikkerhet

* Identitetsforvaltning

* Tilgangsstyring

* Tillitstjenester

* Informasjonsforvaltning

* Avtalehåndtering

* Lover og regler

* Semantikk

* Feilhåndtering (rollback, kompenasasjonstransaksjoner)

* Transaksjonsstøtte

* Protokoller og formater

////
