:lang: no
:doctitle: Konvensjoner for navning i Archimate-modeller
:keywords: Archimate

include::../plattform_felles/includes/commonincludes.adoc[]

== Generelt
Archimate-standarden gir noen retningslinjer for navning av de ulike modellkonseptene. Disse retningslinjene bør følges så langt det passer, men norsk språk er forskjellig fra engelsk og god navning på norsk kan være annerledes enn på engelsk. Her gis noen presiseringer og ytterligere anbefalinger om navning og formatering.

Slike felles konvensjoner tjener flere formål; først og fremst at det skal bli enklere å forstå hva som menes for de som leser modellene.

Et viktig hensyn er at vi må støtte flerspråklighet for å kunne kommunisere og samarbeide ut av Norge. I praksis innebærer dette at vi må kunne produsere og presentere tekst på engelsk og norsk.

== Støtte for alternative språk
Alle modellkonsepter 


== Om navning av attributter
Se link:archimate-attributter.adoc[om archimate-attributter].


== Presiseringer om navning av modellkonsepter

=== Prosess
Archimate-standarden sier: The name of a business process should clearly indicate a predefined sequence of actions, and may include the word “process”. Examples are “adjudicate claim”, “employee on-boarding”, “approval process”, or “financial reporting”.

=== Kapabilitet
Om det asser 

Bruk eventuelt verb slik at det passer med ..


Aktør eller system må være i s tand til å ......