:lang: no
:doctitle: Altinn tilgangsstyring
:keywords: nasjonal arkitektur, virksomhetsarkitektur
:audience: alle
include::../plattform_felles/includes/commonincludes.adoc[]

== Løsningsnavn
*Altinn tilgangsstyring*

== Kort beskrivelse
Altinn Tilgangsstyring (tidligere Altinn Autorisasjon), betegner et sett tjenester og funksjoner knyttet til å styre hvem som kan bruke en digital tjeneste. 
Bruker (person eller virksomhet) autentiseres av ID-porten eller en egen løsning for autentisering i Altinn, før Altinn overtar og gir adgang til å benytte data eller tjenester basert på autorisasjon. 
Autorisasjon kan være basert på hjemmel, delegert tilgang, fullmakter, eller samtykke til å dele data og Altinn benytter eksterne autorisasjonskilder (Enhetsregisteret, DSF) i beslutning om autorisasjon.
I tillegg til å ivareta selve tilgangsstyringen, omfatter løsningen også logger (""mine data som er levert ut basert på mine samtykker""), og som kan bygges ut til mer fullstendige oversikter iht. behov avlevert av GDPR e a. 
Disse løsningene skal kunne benyttes som frittstående moduler, uavhengig av om man benytter andre moduler/tjenester/funksjoner i Altinn. F eks kjøres det en POC på bruk av løsningen for helsenorge.no. Løsningen er under utvikling i et eget prosjekt kalt Helhetlig tilgangsstyring (HELT), og innsikts- og spesifikasjonsarbeid pågår høsten 2018. Herunder samspillet med den ""videreutviklete"" ID-porten (OAuth mv).

== Forvaltningsansvarlig
Brønnøysundregistrene v/ avd Digitalisering (Altinn-organisasjonen)

== Målgruppe
Primært offentlige virksomheter som utvikler og tilbyr digitale tjenester til sine brukere, både innbyggere og virksomheter. Det jobbes for at data og tjenester også skal kunne tilbys virksomheter i privat sektor, og således bli en plattform for innovasjon og verdiskaping også i privat sektor.

== Funksjonalitet (as-is)
Hjemmelbasert Autorisasjon (f eks i kraft av et ansettelsesforhold eller registrert regnskapsfører/revisor)
Tilgang kan delegeres (leder gir tilgang til underordnet, eller virksomhet til regnskapsfører etc)
Fullmakt basert tilgang (f eks foreldre til barn, advokat for en privatperson, vergemål mv)
Samtykke basert tilgang (samtykkebasert innhenting av opplysninger, f eks ved en søknad om boliglån)
I tillegg til å ivareta selve tilgangsstyringen, omfatter løsningen også logger (""mine data som er levert ut basert på mine samtykker""), og som kan bygges ut til mer fullstendige oversikter iht. behov avlevert av GDPR e a.

Disse løsningene skal kunne benyttes som frittstående moduler, uavhengig av om man benytter andre moduler/tjenester/funksjoner i Altinn.

== Føringer for bruk
Samme som Altinn tjenesteplattform.

== Bruk
Benyttes til å delegere tilganger og rettigheter på vegne av andre 

== Datakvalitet
Altinn tilgangsstryring bruker roller registrert i Enhetsregisteret(ER) grunnlaget for tilgangsstyring til virksomheter. I dag oppleves kvaliteten som tilfredstillende, noe bruken av disse dataene i Altinn har bidratt til. 

== Dagens sourcingmodell
Samme som Altinn tjenesteplattform.

== Effekt/produktregnskap
-

== Merkantile forhold
Alle komponenten i Altinn bortsett fra DPV finansieres etter samme prinsipper:

* Utvikling av Altinn-løsningen skal finansieres sentralt via BRs budsjetter.
* Tjenesteeiere skal finansiere kostnader knyttet til drift og driftsrelatert applikasjonsforvaltning
* Utvikling og vedlikehold av sluttbrukertjenestene finansieres særskilt enten av en enkelt
tjenesteeier eller som egne satsninger.

== Utviklingsplaner og finansiering
Plattformen er underveis i et større videreutviklingsløp; hvor man ser tjenesteplattformen (både tjenesteutviklingsløsningen beskrevet over, og også avansert funksjonalitet rundt API-management mv) i samspill med Altinn Autorisasjon (og ID-porten), og de felles katalogene fra informasjonsforvaltning, i sammenheng. Det er for 2018 tildelt 100 millioner til videreutvikling i 2018 (inkludert også Altinn Autorisasjon og API-katalog). De første leveransene kommer i 4 kvartal, og det vil bli kontinuerlige leveranser gjennom 2019 og 2020.

== Langsiktig roadmap
Stor satsing på Helhetlig tilgangsstyring nå- videreutvikling av dagens autorisasjonsløsning 

== Overlappende løsninger
Nei, det finnes ikke andre løsninger i forvaltningen i dag.

== Gjenbrukspotensiale
Stort gjennbrukspotensiale.

== Interoperabilitet
-

== Integrasjon/samhandling
Spiller sammen med autentiseringskomponenten ID-Porten

== Avhengigheter
Avhengig av resten av Altinn-plattformen og ID-porten

== Arkitekturprinsipper
Systemdokumentasjon finnes på https://github.com/Altinn/docs

== Annet
-

